author: Jimmy
name: Excelsior
version: 1.0.0
main: excelsior.Excelsior
api-version: 1.13
depend: [ExcelsiorCore]
commands:
  test:
    usage: /<command>
    description: To test things
  arena:
    usage: /<command>
    description: Arena commands

